#!/bin/sh /etc/rc.common
# Copyright (C) 2019 By [CTCGFW] Project OpenWRT

START=99
STOP=10

enabled="$(uci get baidupcs-web.config.enabled)"
port="$(uci get baidupcs-web.config.port)"
dl_dir="$(uci get baidupcs-web.config.dl_dir)"
baidupcs="$(uci get baidupcs-web.config.baidupcs)"


baidupcs=$baidupcs/BaiduPCS-Go

start() {

	stop
	[ "$enabled" == "1" ] || exit 0
	mkdir -p "${dl_dir}"                                                                      

	chmod +x $baidupcs 
	$baidupcs config set -savedir="${dl_dir}" >/dev/null 2>&1
	$baidupcs web --port "${port}" --access >/dev/null 2>&1 &
}

stop() {
	killall $baidupcs >/dev/null 2>&1
}
