# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for frpc
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-frpc
PKG_VERSION:=2.0
PKG_RELEASE:=27

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

