#!/bin/sh



	uci set system.@system[0].zonename=Asia/Shanghais
	uci set system.@system[0].timezone=CST-8
	uci commit system

	uci set luci.main.lang=zh_cn
	uci commit luci


        uci set network.globals.ula_prefix='2001:240:dddd::1/64'
        uci set network.lan.ip6assign='64'
        uci set network.lan.ipaddr='10.10.10.10'
        uci set network.wan6.peerdns='0'
        uci set network.wan6.dns='2001:4860:4860::8888'
        uci set network.wan.ipv6=1
        uci set dhcp.lan.ra='server'
        uci set dhcp.lan.dhcpv6='server'
        uci set dhcp.lan.ra_management='1'
        uci set dhcp.lan.ra_default='1'
        uci commit network

       
        uci set dhcp.lan.ra_management='1'
        uci set dhcp.lan.ra_default='1'
        uci set dhcp.lan.leasetime='30m'
        uci set dhcp.lan.start='10'
        uci commit dhcp
    

        uci set fstab.@global[0].anon_mount=1
        uci commit fstab 


sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up


sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='openwrt'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

echo 0xDEADBEEF > /etc/config/google_fu_mode

echo ". /opt/etc/profile" >> /etc/profile

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache


exit 0



