#!/bin/sh /etc/rc.common

START=99
STOP=13
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	config_load "entware"
	config_get enable config enable 0
	[ "$enable" -eq 0 ] &&	exit 0

    path=$(config_get config path)

    verysyncpath=$(config_get config verysyncpath)
	verysync=$(config_get config verysync)

    qBittorrent=$(config_get config qBittorrent)

    swap=$(config_get config swap)

    optPath=$path/opt
              
    pre_start 
    mkdir -p /opt 
    mount -o bind  $optPath /opt
    chmod -R 777 opt
    /opt/etc/init.d/rc.unslung start

    if [ "$verysync" -eq 1 ]; then
        cd $verysyncpath/verysync
       ./verysync -home ./config -gui-address=0.0.0.0:8886 -logfile="/tmp/verysync.log" -no-browser >/dev/null &
    else 
        kill -9 `pgrep verysync`
        
    fi 

    if [ "$qBittorrent" -eq 1 ]; then
        echo "start"
    else 
        kill -9 `pgrep qBittorrent-nox`
    fi 

    if [ "$swap" -eq 1 ]; then
        on_swap
    else 
        swapoff /opt/.swap
    fi 



    
    sh /opt/feng.sh&
  
}

stop() {

        /opt/etc/init.d/rc.unslung stop
        kill -9 `pgrep verysync`

}
	 
restart() {
	stop
	sleep 10
	start
}

on_swap()
{
    status=$(cat /proc/swaps |  awk 'NR==2')
    if [[ -n "$status" ]]; then
        echo "Swap已启用"
    else
        if [[ ! -e "/opt/.swap" ]]; then
            echo "正在生成swap文件，请耐心等待..."
            dd if=/dev/zero of=/opt/.swap bs=1024 count=524288
            # 设置交换文件
            mkswap /opt/.swap
            chmod 0600 /opt/.swap
        fi
        # 启用交换分区
        swapon /opt/.swap
        echo "现在你可以使用free命令查看swap是否启用"
    fi
}

pre_start(){

    if [ ! -d "$optPath" ]; then

        mkdir $optPath 
	    mkdir -p /opt
        mount -o bind $optPath /opt
        wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | /bin/sh
        echo ". /opt/etc/profile" >> /etc/profile
        source /etc/profile
        opkg update
        opkg install python tar qBittorrent
    fi
}
